name: Deploy to Stream Server

on:
   push:
      branches:
         - main

jobs:
   deploy:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout code
           uses: actions/checkout@v3

         - name: Set up Docker Buildx
           uses: docker/setup-buildx-action@v2

         - name: Login to Docker Hub
           uses: docker/login-action@v2
           with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

         - name: Build and push Docker image
           run: |
              docker build -t yourusername/serverVideoStream:latest .
              docker push yourusername/serverVideoStream:latest

         - name: Deploy to server
           env:
              SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
              SERVER_IP: ${{ secrets.SERVER_IP_STREAM }}
              SERVER_USER: ${{ secrets.SERVER_USER_STREAM }}
           run: |
              ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ env.SERVER_USER }}@${{ env.SERVER_IP }} << 'EOF'
                docker pull yourusername/serverVideoStream:latest
                docker stop serverVideoStream || true
                docker rm serverVideoStream || true
                docker run -d --name serverVideoStream -p 3001:3001 yourusername/serverVideoStream:latest
              EOF


              name: Deploy
